# Required
Disease/Phenotype terms: heart failure, cardiomyopathy, coronary artery disease, cardiovascular disease, hypertension, atrial fibrillation, arrhythmia, myocardial infarction, heart valve disease

# Optional
Additional associated terms: heart, cardiovascular, artery, arterial, aorta, ventricle, atrial, kidney, renal, diabetes, obesity
Diseases/Phenotypes to exclude: 
